# Generated by Django 4.0.4 on 2022-08-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_customuser_image_alter_customuser_last_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_uuid',
            field=models.CharField(default=None, max_length=23, unique=True),
        ),
    ]
