# Generated by Django 4.0.4 on 2022-08-15 12:34

import django.contrib.auth.validators
from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_post_post_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Такое имя пользователя занято.'}, max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), main_app.validators.custom_username_validator], verbose_name='Имя пользователя'),
        ),
    ]
