# Generated by Django 4.0.4 on 2022-08-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст'),
        ),
    ]
