# Generated by Django 4.0.4 on 2023-04-05 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogs_first_user', to=settings.AUTH_USER_MODEL, verbose_name='Первый пользователь'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='second_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogs_second_user', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь'),
        ),
        migrations.AddField(
            model_name='conservationmessage',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_app.conservation', verbose_name='Беседа'),
        ),
        migrations.AddField(
            model_name='conservationmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='conservation',
            name='members',
            field=models.ManyToManyField(related_name='conservations', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='conservation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.CheckConstraint(check=models.Q(('owner', django.db.models.expressions.F('second_user')), _negated=True), name='check_self_dialog'),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.UniqueConstraint(fields=('owner', 'second_user'), name='unique_dialog'),
        ),
    ]
